In [1]:
import pandas as pd

In [114]:
final_caste = pd.read_csv("final_caste_with_source.csv")

In [115]:
final_caste

            Caste                                          subcastes source
0          AARAKH  ['MOOTHI', 'YADAV', 'AARAKH', 'ARAKVANSHIYA', ...     mf
1          ABBASI                     ['ABBASI', 'BHISHTI', 'SAKKA']    gov
2           ABDAL                                          ['ABDAL']    gov
3       ABLAKAROR                                      ['ABLAKAROR']     mf
4            ABOR                                           ['ABOR']    gov
...           ...                                                ...    ...
2216  YOGEESWARAR                                    ['YOGEESWARAR']    gov
2217         YOGI              ['JOGI', 'JUGI NATH', 'NATH', 'YOGI']     mf
2218    YRAKITHER                                      ['YRAKITHER']     mf
2219       ZAMRAL                                         ['ZAMRAL']    gov
2220          ZOU                                            ['ZOU']    gov

[2221 rows x 3 columns]

In [116]:
import pandas as pd
import ast

# Define the keywords for Muslim communities (all lowercase)
muslim_keywords = [
    "muslim", "saiyad", "syed", "sheikh", "qussab", "khan", "pathan",
    "ansari", "momin", "mullaji", "mughal", "naqvi", "rizvi", "sunni", "shia",
    "malik", "quraishi", "qureshi", "farooqui", "usmani", "peer", "fakir", "mufti"
]

# Function to check if any Muslim keyword is present
def contains_muslim_any(text):
    text = str(text).lower()
    return any(keyword in text for keyword in muslim_keywords)

# Convert Subcastes column from string to list
final_caste['subcastes'] = final_caste['subcastes'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else [])

# Function to check both caste and subcastes
def is_muslim_row(row):
    if contains_muslim_any(row['Caste']):
        return True
    return any(contains_muslim_any(sub) for sub in row['subcastes'])

# Apply filter
muslim_df = final_caste[final_caste.apply(is_muslim_row, axis=1)]
non_muslim_df = final_caste[~final_caste.apply(is_muslim_row, axis=1)]

In [117]:
muslim_df.reset_index(drop=True, inplace=True)

In [118]:
muslim_df.to_csv("muslim_caste.csv", index=False)

In [119]:
muslim_caste_list1 = muslim_df['Caste'].tolist()

In [120]:
muslim_caste_list2 = muslim_df['subcastes'].explode().dropna().unique().tolist()

In [121]:
muslim_caste_list2

['BHENIL',
 'GOND',
 'DHIMAR',
 'BINJHWAR',
 'KANWAR',
 'BHILALA',
 'SIDAR',
 'BHEND',
 'HANDSA',
 'HEMRAM',
 'KHAN',
 'BHENA',
 'NAGARCHI',
 'DHANWAR',
 'GOARI',
 'MARANDI',
 'ADIWASI',
 'SARTHI',
 'BARGAH',
 'THETHWAR',
 'AYAR',
 'LALHARIA',
 'GAWALI',
 'RAO',
 'TURI',
 'BRAJWASI',
 'TELI',
 'RAWAT',
 'BAGDE',
 'SHAH',
 'LINGAYAT-GAOLI',
 'RAUT',
 'GURJAR',
 'BERICHA',
 'GOP',
 'GWARA JADAV',
 'GAWARI',
 'SONWANI',
 'BHARVAD',
 'YADAV',
 'KUMAWAT',
 'AHIR',
 'KHANNA',
 'ASKE',
 'WANJARE',
 'GOPAL',
 'SISODIA',
 'NARNAVRE',
 'GOWRA',
 'GOLI',
 'RATHORE',
 'SAHU',
 'BARGAHI',
 'JAMRE',
 'GWARA',
 'JADAV',
 'RAI',
 'SORATHA',
 'GAWLI',
 'GWALA',
 'RAUT THETHWAR',
 'PALIWAL',
 'GOWARI',
 'ANSARI',
 'BADHRIA',
 'KHARADI',
 'KHATI',
 'DHEEMAN',
 'MAGHIYA',
 'BADAI',
 'BADHAI',
 'KHARADA',
 'VISHWAKARMA',
 'HARIJAN',
 'TARKHAN',
 'JANGRA-BRAHMIN',
 'NISHAD',
 'PANWARI',
 'RAMGARHIA-SIKH',
 'PANCHAL',
 'SUTHAR',
 'RAMGARHIA',
 'CHOURSIA',
 'BADHIRA',
 'MISTRY',
 'SHARMA',
 'JANGADA',
 'VISWAKARMA',
 'TARKHAN.',
 'BADHEI',
 'BINDHANIA',
 'CHAURASIA',
 'BARHAI',
 'JANGID',
 'SUTRADHAR',
 'ASRATI',
 'SINGLA',
 'KANSAL',
 'ORIYABANIYA',
 'TUREHA',
 'BANIYA',
 'VARSHNEY',
 'ORIYAMUNDA',
 'ARORA',
 'CHOUDHARY',
 'GUPTA',
 'AGARAWAL',
 'BARNAWAL',
 'SINGHAL',
 'KHANDEL',
 'GARG',
 'JAISWAL',
 'AGARWAL',
 'KESARBANI',
 'MODI',
 'SUNARI',
 'KESRI',
 'GOYAL',
 'KESHRWANI',
 'BANSAL',
 'SHAHU',
 'JINDAL',
 'PADAIYACHI',
 'RANA',
 'AYODHABASI',
 'JAIN',
 'POWAR',
 'GOEL',
 'BANNIYAR',
 'MAHAJAN',
 'SUGALI.',
 'DHALIA',
 'LAMAN BANJARA',
 'DHURIYA',
 'RANKI',
 'MATHURA',
 'MUKERI',
 'LAMANI',
 'DHALIA BANJARA',
 'LABHANA',
 'LAMBADE LAMBHANI CHARAN BANJARA LABHAN MATHURA LABHANI',
 'BAMANIA BANJARA',
 'SUKALI',
 'RAVANA',
 'LAMBARA',
 'BALADIA',
 'BANJARI',
 'RANGREZ',
 'BANJARI GOAR BANJARA LAMBADA',
 'MAKRANI.',
 'GORMATI',
 'MATHURA LABHAN',
 'MATHURA BANJARA KACHIKIWALE BANJARA LAMAN BANJARA LAMAN',
 'MEKRANI',
 'GAMETIA',
 'LABHANA LABAN',
 'NAVI BANJARA',
 'NAYKADA',
 'LAMNE',
 'LAMAN',
 'LAMBANI',
 'RATHOR',
 'LAMANI LABAN DHALI',
 'LABANA',
 'SUGALI',
 'BANJARA',
 'DHADI',
 'LAMBADA',
 'LAMBADI',
 'MAKRANI',
 'LABAN',
 'BANJARI MATHURA',
 'LAMBARA LAMBHANI',
 'RANKIA',
 'MANSURI',
 'JOGI BANJARA',
 'LAMBANA',
 'CHANDWAR',
 'KACHIRIWALA BANJARA',
 'VAISHNAV',
 'BAMANIA BANJARA LAMAN',
 'NAYKADA LAMBANA',
 'MATHURA BANJARI',
 'NAYAK',
 'CHADAWA',
 'DHARI SINGARI NAVI BANJARA',
 'BHATI',
 'SUNKAR',
 'MUSLIM BELDAR',
 'OD',
 'TAWAR',
 'BELDAR',
 'BHANGI',
 'LALBEGI',
 'BALMIK',
 'BARWASIA',
 'RUKHI',
 'RUSHI',
 'ZADMALLI',
 'ZAMPDA',
 'BAKSHI PANCH',
 'UPADHAYAY',
 'JAMPHODA',
 'OLGANA',
 'BARWASHIA',
 'CHURA',
 'VALMIKI',
 'BALMIKI',
 'DHARKAR',
 'KORAR',
 'MALKANA',
 'HELA',
 'ZAMPADA',
 'MEHTAR',
 'HALALKHOR',
 'SETIA',
 'NARGESH',
 'BAKAULEY',
 'SHAITE',
 'BAGHEL',
 'JHHILA',
 'MORI',
 'GWALE',
 'BHEL',
 'WAGE',
 'DODWAL',
 'VARMAN',
 'ROMDADE',
 'MUKATIB',
 'SOLANKI',
 'SONAR',
 'DAMAR',
 'BHURIYA',
 'WASKALE',
 'GANGWAL',
 'BALKEY',
 'SAITEY',
 'MALVIA',
 'AKOLIYA',
 'AWASE',
 'BHAGE',
 'CHAUHAN',
 'JILVE',
 'DHILE',
 'KHARTE',
 'MUDALJE',
 'NIHAL',
 'KHATIYA',
 'NINGWAL',
 'KOLH',
 'TADWLA',
 'MANKOLI',
 'DWAR',
 'GORE',
 'BADDLE',
 'NARGAVE',
 'KUSHWAHA',
 'BHILA LA',
 'BHEW',
 'MANDOLI',
 'DORWAR',
 'DARBAR',
 'KANASHE',
 'CHONGAR',
 'MOZALDA',
 'SAMANTA',
 'TRIVEDI',
 'PRAJAPATI',
 'HAVASALA',
 'BRHAMIN',
 'PUROHIT',
 'PACHORI',
 'CHATURVEDI',
 'SAIFI',
 'DEVILA',
 'OTHERS',
 'SHUKLA',
 'BHARADWAJ',
 'DEWEDI',
 'VAIDHIKA',
 'DADHICH',
 'PAREEK',
 'VISHVA S',
 'MAHA-BRAHMAN',
 'DUBEY',
 'HAVJAK',
 'AUDICH',
 'IYYAR',
 'VAIDIK',
 'DANUA',
 'RAJGOR',
 'SIDHANTHI',
 'IYANGAR',
 'HAUYAK',
 'SAMRATH',
 'AYYANGAR',
 'MOHABRAHMAN',
 'VASSIST',
 'BRAHAMIN',
 'GAUTAM',
 'RAJPUROHIT',
 'GOSWAMI',
 'UPADHYAY',
 'MAHANT',
 'BHATT',
 'BESNAB',
 'SANYAL',
 'DIXIT',
 'BHARGAV',
 'OJHA',
 'AYAN',
 'RAMPAL',
 'BRAHIMAN',
 'TRIPATHI',
 'GOGNA',
 'BAJPAI',
 'BALABHADRA',
 'CHASA',
 'DESHASTHA',
 'SASANI',
 'ACHARYA',
 'BAIRAGI',
 'THAKUR',
 'PARDESI',
 'SONI',
 'DEVEDI',
 'TYAGI',
 'UPADHAYA',
 'GIRI',
 'ATRI',
 'HAVYAKA',
 'JOSHI',
 'PUJARI',
 'IYER',
 'PANDEY',
 'GOSAWMI',
 'VAISHNA V',
 'KAUSHIK',
 'BHATTAMISHRA',
 'KAIBARTA',
 'SANDILYA',
 'KRUSHMAPAKSHI',
 'VYAS',
 'TAPODHAN',
 'BRHAMAN',
 'TURKHAN',
 'GANDHARU',
 'DWIVEDI',
 'JHANGRA BRAHMAN',
 'ADHIT',
 'RARHI',
 'DAKHINORIYA',
 'AJER',
 'SARASWATI',
 'GAUR',
 'MISHRA',
 'BRAHMAN',
 'BAISNAB',
 'SHRMA',
 'BARENDRA',
 'SARASWAT',
 'MUDGIL',
 'KOTTA',
 'BRAHAMAN',
 'PATHAK',
 'AGNIHOTRI',
 'PORASA',
 'KUTCHHI',
 'CHAUBEY',
 'VASUDEV',
 'SWAMI',
 'DHIMAN',
 'AADISAIVER',
 'BAJPAYEE',
 'JADURBADE',
 'BRAHMIN',
 'LOHAR',
 'TIWARI',
 'VAID',
 'AWASHTHI',
 'BHARATI',
 'QASSAI',
 'CHIKWA',
 'KASAI',
 'CHIKWA QASSAB',
 'QURAISHI',
 'CHAK',
 'CHIKVI',
 'KASSAB',
 'DANGASHIA',
 'DEKKANI MUSLIM',
 'KAMDAY',
 'KHEWAT',
 'KEWAT',
 'VRITIYA SONDHIYA',
 'MALLAH',
 'KIR BRITIYA',
 'TARAIL',
 'KAMARE',
 'SONDHIYA',
 'BHISTI',
 'MACHHANDAR',
 'KASHYAP',
 'SAKKA',
 'DHIMER BHOI',
 'BHATIYAR',
 'TURAHA',
 'DOGARWAR',
 'SHEIKH-ABBASI',
 'MORDE',
 'NAVDA',
 'MEHRA',
 'VRITIYA',
 'JHIMAR',
 'NAWDA',
 'DHINWAR',
 'DHIMER',
 'KAHRA',
 'NAVDA TURAHA KEWAT KIR BRITIYA',
 'KASYE RAJPUTS',
 'MESHRAM',
 'RAJPUT',
 'KAHAR',
 'KASHYAP-RAJPOOT',
 'BHOI',
 'TURSIB',
 'KAHRA DHIWAR MALLAH NAWDA',
 'JHINWAR',
 'DHIWAR',
 'FAKIR BHANDARWALA',
 'SHAM',
 'ALVI',
 'MIYAN',
 'SAIN',
 'FAKIR',
 'FAKIR INCLUDING ALVI-FAKIR',
 'MANIHAR',
 'FAQUIR',
 'FAQIR',
 'FAKEER',
 'SHEIKH',
 'MUSLIM GAWLI',
 'GHUMAIR',
 'GOLLA',
 'GOUDIA GOLA',
 'LAXMINARAYAN GOLA',
 'MATHURAPURIA GOUDA',
 'MEKALA GOLLA',
 'PUNNU GOLLA',
 'GOLA RANA',
 'GOUDA',
 'SHOLAKHANDIA',
 'GOPALA',
 'GOUR',
 'GOUDO',
 'MAGHADA GOUDA',
 'GOLA',
 'SADGOP',
 'GOPE',
 'NANDA GOUDA & KANJA GOUDA',
 'DUMAL GOUDA',
 'GOPAPURIA GOUDA',
 'SADGOPE',
 'GORI',
 'GOHIL',
 'PATEL',
 'GUJARA',
 'MAHESHWARI',
 'KASANA',
 'GUJJAR',
 'NAGAR',
 'BAKARWAL',
 'GUJAR',
 'GUZAR',
 'DHAMA',
 'PARMAR',
 'DRAWAT',
 'GOOJAR',
 'GUJJAR(MUSLIM)',
 'MAUN',
 'LUNJ',
 'HER',
 'PAYAL',
 'GREWAL',
 'DHANKAR',
 'KANG',
 'SIWATCH',
 'SHEORAN',
 'MALIK',
 'KHAYALI',
 'KOKKAR',
 'JAT SIKH',
 'KALERI',
 'SAMRA',
 'HANS',
 'DHAKA',
 'JAKHAR',
 'BHAMBHO',
 'GILL',
 'MEEL',
 'TEWATIYA',
 'THIR',
 'SIROHI',
 'KSHLIYA',
 'BHATTI',
 'BIRIKHI',
 'MAAN',
 'JADGE',
 'SOHAL',
 'KAITH',
 'GUBANDA',
 'MOD',
 'CHAHAL',
 'BHANGU',
 'GHUMAN',
 'SAHRAWAT',
 'KEOL',
 'RANDHAWA',
 'BHINDER',
 'CHAUDHARI',
 'PAWAR',
 'MADAN',
 'SARAN',
 'JAKAHD',
 'DEOL',
 'CHEL',
 'KHACERI',
 'PANNU',
 'GODRA',
 'CHOPRA',
 'JATSIKH',
 'LOHAN',
 'MANN',
 'PUNIYA',
 'SIHAG',
 'SAMARAN',
 'KUNDU',
 'NAIN',
 'SHEDKAND',
 'THALODI',
 'BENIWAL',
 'BHAL',
 'JUDGE',
 'CHATRAWAL',
 'MORWAL',
 'PANGHAL',
 'FAGADANA',
 'TATLA',
 'LALLI',
 'BHULLAR',
 'NIJJAR',
 'JAT',
 'JHIWAR',
 'SANDHU',
 'MITHA',
 'MANDAL',
 'MAUR',
 'SIDHU',
 'CHIMMA',
 'CHICHAR',
 'PAKGI',
 'BARAI',
 'BASSI',
 'JANGID BRAHMAN',
 'JHANGRA-BRAHMAN',
 'BADDI',
 'JHANGARA-BRAHMAN',
 'JANGRA BRAHMAN',
 'JANGRA-BRAHMAN',
 'KEER',
 'KABIRPATH',
 'JULAYA',
 'TARIYA',
 'KABIRAM',
 'JULAHA',
 'TARI',
 'JULAHE',
 'KABIRPANTHI',
 'GARANA',
 'JULAHA-MOMIN',
 'MOMIN-ANSARI',
 'JULAHA-ANSARI',
 'MOMIN',
 'ALI',
 'JULLAHA',
 'KOLI',
 'KANJIRBHAT',
 'KANJARA â€“ BHATTA',
 'KHANJARBHAT',
 'KANJARA-BHATTA',
 'KANJIRBHAAT',
 'KANSARI',
 'QASSAB-QURESHI',
 'ARE KASAI',
 'KASAB',
 'ARI KATIKELU',
 'QUASAB',
 'KATUKA KATUGA',
 'MARATTI',
 'SURYAVAMSHA KSHATRIYA',
 'KASSAB QUSSAB',
 'KALAL KHATIK',
 'KISBI',
 'KHATIK',
 'KASAI-QURAISHI',
 'KATIK',
 'KASABI',
 'ARAY',
 'QASSAB',
 'PATHAN',
 'MUNDA',
 'ODUKHANDAYAT',
 'SRESTAKHANDAYAT',
 'MAHANAIK',
 'KANDARA',
 'KHANDAYAT',
 'KHANDELWAL',
 'KHANDNALS',
 'KHANDU',
 'MIRDHA',
 'KHANGAR',
 'KANERA',
 'KHANGHERA',
 'KHANT',
 'KHATHIYA',
 'JAGARA',
 'UTTAM',
 'KHATKI',
 'BAMANIYA',
 'CHIK',
 'JANGARH',
 'NATH',
 'SONKAR',
 'DHAMAN',
 'KASAI-QURESHI',
 'KHATWA',
 'KHATWE',
 'QURESHI',
 'SEMAR',
 'KHATGUNE',
 'HALARI',
 'CHAMADIA',
 'ORHKHANDAYAT',
 'KHETRIYA',
 'KHOTTA MUSLIM',
 'KHARWA',
 'DONGAR KOLI',
 'KOLI PATEL',
 'MAHAVAR',
 'KHARWI',
 'BARI',
 'MAHADEVKOLI',
 'KOLI MAHADEV',
 'BHEBARIA-KOLI',
 'CHRISTIAN KOLI',
 'PANBHARE SON KOLI',
 'BARIA-KOLI',
 'KOLCHA',
 'GHEDIA KOLI',
 'CHUVALIA KOLI',
 'CHUMBLE',
 'MALHARKOLI',
 'KORI',
 'KHARVA',
 'KOLI SURYAVAMSHI VAITI',
 'KOLI KADIA.',
 'RATHWA-KOLI',
 'KOLGHA',
 'KHARVI',
 'DIVECHA KOLI',
 'KOLI DHOR',
 'KHARWA-KOLI',
 'AHIR KOLI',
 'MALHAR',
 'PAN KOLI',
 'GABIT',
 'TOKRE KOLI',
 'MACHIMAR KOLI',
 'KHANDESHI KOLI',
 'MANGELA',
 'MANGALA',
 'KOLI MACHHI',
 'IDARIA-KOLI',
 'KOLI KHANIA',
 'KUSHIARI',
 'PARH',
 'KUPADHAR',
 'WADHAI',
 'BAWRI',
 'LUHAR SAIFI',
 'NADRA',
 'BHUBHALIA',
 'SHAKHALA',
 'HUNGA LOHAR',
 'LOHPATA',
 'SHER',
 'KHATAWALI',
 'GAROLA',
 'BHUHALIA-LOHAR',
 'BHUBALIA-LOHAR',
 'GADILOHAR',
 'LUHAR',
 'LOHPETA',
 'YADA V',
 'CHATRI',
 'VERMA',
 'JAGADE',
 'LOHRA',
 'DODI',
 'LOHPITA',
 'SURI',
 'PRJAPATI',
 'NAGAURI LUHAR',
 'AMRA',
 'GADOLEY',
 'MISTRI',
 'VISHKARMA',
 'DHELE',
 'KALRI',
 'LOHAR- GADA',
 'MULTANI LUHAR',
 'DUPAD',
 'ORIYAKAMAR',
 'PANCHAI',
 'LOHARA',
 'GADELA',
 'TILAK',
 'KUSMETE',
 'MAJHI',
 'BHATWAR',
 'PATNI MUSLIM',
 'MAL MUSLIM',
 'VAJIR',
 'SAYYAD',
 'RADHE MANG',
 'MANG GARODI',
 'MADARI',
 'GARUDI',
 'MANG',
 'MANG MAHASI',
 'MANG GARUDI',
 'MANGIA',
 'MATANG',
 'MANG MAHASHI',
 'DANKHANI MANG',
 'MANG-GARUDI',
 'DANKHNI MANG',
 'MINIMADIG',
 'MANSUR',
 'MOMINANSARI',
 'ANSAR',
 'RISHI',
 'RAVIDAS',
 'CHAMAR MUSLIM',
 'MUCHI',
 'MUGHAL',
 'BEG',
 'MEENA',
 'MUSKHAN',
 'MUSLIM',
 'JALARI',
 'MUJAHID',
 'NADAG',
 'SWETAMBAR',
 'SHAIK',
 'LEPPAI',
 'JAMARI',
 'LABBAI',
 'PANCHAMSALI',
 'BYARE',
 'KUDARI',
 'DUDEKULA',
 'JAMAMITK',
 'BOHRA',
 'JALLENI',
 'SHAIKH',
 'CHEEMALA',
 'MEDAR',
 'JHAMALA',
 'MULLA',
 'JAMAN',
 'NAPAE',
 'NAIKA',
 'NADAK',
 'RABBAI',
 'NADAR',
 'SWNNR',
 'SYED',
 'WADE',
 'SAYED',
 'RAVUTHUR',
 'NADAF',
 'RAWTHER',
 'SUNNI',
 'GUNJE',
 'MATESHP',
 'MAPPILLA',
 'MUSLIM BARUJIBI',
 'BARUI',
 'MUSLIM RELIGION BHANGI',
 'LALBEG',
 'KHAKROB',
 'THE MEMBERS OF WHICH ARE ACTUALLY IN THE SAFAI KARAMCHARI PROFESSION',
 'MUSLIM BHATIYARA',
 'MUSLIM BISWAS',
 'MUSLIM CHUTOR MISTRI',
 'MUSLIM DAFADAR',
 'OSTAGAR',
 'MUSLIM DARJI',
 'SIDDIQUI',
 'MUSLIMDARJI',
 'IDRISHI',
 'SULEMANI',
 'MUSLIMDHOBI',
 'DHUNIYA',
 'KASSAR',
 'BAKSH',
 'HASHMI',
 'MUSLIMGUJAR',
 'MUSLIM HALDAR',
 'MUSLIMHALWAI',
 'MUSLIM JAMADAR',
 'MUSLIM KALANDAR',
 'MUSLIM KAYASTHA',
 'MUSLIM LASKAR',
 'MUSLIMLOHAR',
 'MUSLIM MADARI',
 'JADOOGAR',
 'SAAPWALE',
 'GAARUDI',
 'MUSLIM MALI',
 'MUSLIM MANYAR',
 'MANIYAAR',
 'MANERI',
 'MUSLIM MOLLA',
 'BALWAR',
 'TURKATA',
 'MUSLIMNAI',
 'MUSLIM NEHARIYA',
 'MUSLIM PENCHI',
 'MUSLIM PIYADA',
 'MUSLIM RAJMISTRI',
 'GADDI',
 'IRAQI',
 'MUSLIMRAJPUT',
 'SAIYED',
 'MUSLIMSALMANI',
 'MUSLIM SANPUI',
 'SAPUI',
 'MUSLIM SARDAR',
 'MUSLIMTELI',
 'DERWAL',
 'PILLAI',
 'THIYA',
 'CHETTIAR',
 'KURUP',
 'VELUTHODATHU NAIR',
 'VILAKIKRISHNAN',
 'PICARI',
 'BHATTATHI',
 'PATTAR',
 'NAMBIYAR',
 'CHETTI',
 'PANICKAR',
 'VLLAKIAM',
 'DEVARA',
 'R.C.NADAR',
 'NAMBUTHIRI',
 'KARTHA',
 'VILAKIT',
 'VELUTHEDATHU NAIR',
 'VALAKATHALA',
 'SYRIAN',
 'GUPTHAN',
 'POTHUWAL',
 'VADIAR',
 'MARAR',
 'NAIR',
 'VILAKITHALA',
 'MENON',
 'PENTACOSTAL',
 'ROMAN CATHOLIC',
 'IYYANGA R',
 'VARIAR',
 'THOGATAGERA',
 'THOGATARU',
 'LINGAYAT KURUSHINASHETTY',
 'JHAMKHANA',
 'LINGAYAT BILIMAGGA',
 'KURNI',
 'LINGAYAT NEYGI',
 'SALE',
 'NEIKAR',
 'PADMA SALI',
 'THOGATIGA',
 'JANDRA',
 'PADMA SHALI',
 'AYIRI',
 'THOGATA',
 'JADAR LINGAYAT JADARU SAKULASALE',
 'PATTASALE',
 'KAIKOLAN',
 'THOGATAVEERA KSHATRIYA',
 'SENGUNDHAR',
 'NEKAR',
 'THOGATAVEERA',
 'KURUSHINASETTY',
 'AVIR',
 'SONIGA',
 'SAALE',
 'NEYGI',
 'PATTASALI',
 'THOGAJA PUSHPANJALI',
 'BILIMAGGA',
 'PADMASALE',
 'PAHADIA MUSLIM',
 'RAIGAR',
 'LEELGA R',
 'MIRZA',
 'MEWAD',
 'PANWAR',
 'JATAV',
 'DHUNIA',
 'NADDAF',
 'KABRAKHODU',
 'LADAF',
 'NADAFF',
 'DUDEKULA MANSURI',
 'MANSURI-PINJARA',
 'SAI',
 'DHUNKAR',
 'PINJARA PINJARI',
 'BEHNA',
 'MANSOORI',
 'PINJARA',
 'PINJARI',
 'GANCHI-PINJARA',
 'BHARMORIA',
 'BHADAURIYA',
 'SAKALANI',
 'BARWA',
 'MINYA',
 'GAHLOT',
 'SARANG',
 'TOMAR',
 'RAKWAR',
 'JHALA',
 'MANDHOTRA',
 'BHALAIYA',
 'NADODA',
 'SISODIYA',
 'NAGWAL',
 'BHANDARI',
 'BAGHARIYA',
 'SINGH',
 'BESHEN',
 'KHODI',
 'SHEKHAWAT',
 'MALI',
 'KUMHA',
 'KARADIYA',
 'DADWAL',
 'KHARAL',
 'BRIJWASI',
 'DARAGA',
 'RAJAWAN',
 'KHANDERA',
 'LEVA',
 'BHAMTA',
 'CHANDAWAT',
 'CHANDRA',
 'BALKHARYA',
 'KHADHAKA',
 'LODHI',
 'BADGUJAK',
 'BISEN',
 'SENGAR',
 'RAJAWAT',
 'RANAWAT',
 'BANGAR',
 'RAHTORE',
 'SOMWANSH',
 'KHARWAL',
 'UJJAINI',
 'TAYAL',
 'BARWAL',
 'TANWAR',
 'DEVRA',
 'PALIHAR',
 'DIKHIT',
 'VAGHELA',
 'DHALARIA',
 'PATIYAL',
 'BALHARIYA',
 'RATHVI',
 'BISHT',
 'SHAHI',
 'BHRIGUVANSHI',
 'RAWAL',
 'JARAULIYA',
 ...]

In [122]:
muslim_caste_list = muslim_caste_list1 + muslim_caste_list2

In [123]:
muslim_caste_list_df = pd.DataFrame(muslim_caste_list, columns=['Caste'])

In [124]:
muslim_caste_list_df

         Caste
0      ADIWASI
1         AHIR
2       ANSARI
3       BADHAI
4       BANIYA
...        ...
1182   THATARI
1183  SAMPANGI
1184     PALLA
1185     VADDI
1186   MANJARI

[1187 rows x 1 columns]

In [125]:
muslim_caste_list_df.to_csv("muslim_caste_list.csv", index=False)

In [126]:
import pandas as pd
import ast

# Load the CSV file
df = pd.read_csv("muslim_caste.csv")
df["subcastes"] = df["subcastes"].apply(ast.literal_eval)

# Define Muslim caste list (standardized)
muslim_castes_raw = """
ABBASHI
ALI
ALVI
ANSAR
ARE KASAI
BAKSH
BALWAR
BEG
BEHNA
BHATIYAR
BHISTI
BOHRA
CHAMAR MUSLIM
CHIKWA QASSAB
DEKKANI MUSLIM
DHUNIA
DOGARWAR
DUDEKULA
DUDEKULA MANSURI
FAKEER
FAKIR
FAKIR BHANDARWALA
FAKIR INCLUDING ALVI-FAKIR
FAQIR
FAROOQ
GAARUDI
GADDI
GANCHI-PINJARA
GUJAR
GUJJAR(MUSLIM)
GUZAR
HALALKHOR
HASHMI
HUSSAIN
IDRISHI
IRAQI
JADOOGAR
JAMAN
JULAHA
JULAHA-ANSARI
JULAHA-MOMIN
JULAHE
JULAYA
KASAB
KASABI
KASAI-QURAISHI
KASSAB QUSSAB
KASSAR
KAZI
KHAKROB
KHAN
KHOTTA MUSLIM
LABBAI
LALBEG
LUHAR SAIFI
MADARI
MAKRANI
MAL MUSLIM
MALIK
MALKANA
MANERI
MANIHAR
MANIYAAR
MANSOORI
MANSUR
MANSURI-PINJARA
MAPPILLA
MEHTAR
MEKRANI
MIRZA
MIYAN
MOMIN
MOMIN-ANSARI
MUGHAL
MUJAHID
MUKATIB
MULLA
MUSKHAN
MUSLIM
MUSLIM BARUJIBI
MUSLIM BELDAR
MUSLIM BHANGI
MUSLIM BHATIYARA
MUSLIM BISWAS
MUSLIM CHUTOR MISTRI
MUSLIM DAFADAR
MUSLIM DARJI
MUSLIM DHOBI
MUSLIM GAWLI
MUSLIM GUJAR
MUSLIM HALDAR
MUSLIM HALWAI
MUSLIM JAMADAR
MUSLIM KALANDAR
MUSLIM KAYASTHA
MUSLIM LASKAR
MUSLIM LOHAR
MUSLIM MALI
MUSLIM MANYAR
MUSLIM MOLLA
MUSLIM NAI
MUSLIM NEHARIYA
MUSLIM PENCHI
MUSLIM PIYADA
MUSLIM RAJMISTRI
MUSLIM RAJPUT
MUSLIM RELIGION BHANGI
MUSLIM SALMANI
MUSLIM SANPUI
MUSLIM SARDAR
MUSLIM TELI
NADAF
OSTAGAR
PAHADIA MUSLIM
PATHAN
PATNI MUSLIM
PEERAHI
PINDARI
PINJARA
PINJARA PINJARI
PINJARI
QASSAB
QASSAB-QURESHI
QASSAI
QUASAB
QURAISHI
QURESHI
RABBAI
RANGHAR
RANGREZ
RAVUTHUR
RAWTHER
RIZVI
SAAPWALE
SAI
SAIFI
SAIN
SAIYED
SAPUI
SAYED
SAYYAD
SHAIK
SHEIKH
SHEIKH SARVARI
SHEIKH-ABBASI
SHEIKHPATHAN
SHER
SIDDIQUI
SIHAMUSLIM
SULEMANI
SUNNI
TELI MALIK
TURKATA
VAJIR
"""
# Replace this with your complete Muslim caste list (like earlier)
muslim_castes_set = set(name.strip().upper() for name in muslim_castes_raw.strip().splitlines())

# Split subcastes into Hindu and Muslim
# Split subcastes into Hindu and Muslim (as comma-separated list-like strings)
def split_subcastes(subcastes):
    hindu_caste = []
    muslim_caste = []
    for sub in subcastes:
        sub_clean = sub.strip()
        if sub_clean.upper() in muslim_castes_set:
            muslim_caste.append(sub_clean)
        else:
            hindu_caste.append(sub_clean)
    return pd.Series([", ".join(hindu_caste), ", ".join(muslim_caste)])

df[['hindu_caste', 'muslim_caste']] = df['subcastes'].apply(split_subcastes)

# Expand into separate rows
expanded_rows = []
for _, row in df.iterrows():
    caste_name = row['Caste']
    source = row['source']
    if row['hindu_caste']:
        expanded_rows.append({
            "Caste": f"{caste_name} (Hindu)",
            "Subcastes": row['hindu_caste'],
            "source": source
        })
    if row['muslim_caste']:
        expanded_rows.append({
            "Caste": f"{caste_name} (Muslim)",
            "Subcastes": row['muslim_caste'],
            "source": source
        })

df_expanded = pd.DataFrame(expanded_rows)

# âœ… Filter only Muslim rows (if needed)
df_muslim_only = df_expanded[df_expanded["Caste"].str.endswith(" (Muslim)")].reset_index(drop=True)
df_hindu = df_expanded[df_expanded["Caste"].str.endswith(" (Hindu)")].reset_index(drop=True)


# Optional: save result
# df_muslim_only.to_csv("muslim_only_castes.csv", index=False)

# View first few rows
df_muslim_only

,Caste,Subcastes,source
0,ADIWASI (Muslim),KHAN,mf
1,BANJARA (Muslim),"RANGREZ, MEKRANI, KHAN, MAKRANI",mf_shadi_jeevansathi
2,BELDAR (Muslim),MUSLIM BELDAR,mf_jeevansathi
3,BHANGI (Muslim),"MALKANA, MEHTAR, HALALKHOR",mf
4,BHILALA (Muslim),MUKATIB,mf
...,...,...,...
72,SHEIKH SARVARI (Muslim),"PEERAHI, SHEIKH SARVARI",gov
73,SIHAMUSLIM (Muslim),SIHAMUSLIM,mf
74,SUNNI (Muslim),SUNNI,mf_shadi_jeevansathi
75,TELI (Muslim),"IDRISHI, TELI MALIK, MALIK, JULAHA, PINDARI",mf_shadi_jeevansathi
76,VADDI (Muslim),"DUDEKULA, PATHAN, SHAIK, SAYED",mf

In [127]:
len(df_muslim_only)

77

In [128]:
df_muslim_only.sample(50)

,Caste,Subcastes,source
43,MUSLIM KALANDAR (Muslim),MUSLIM KALANDAR,gov
11,GHUMAIR (Muslim),KHAN,mf
9,FAKIR (Muslim),"FAKIR BHANDARWALA, ALVI, MIYAN, KHAN, SAIN, FA...",mf
39,MUSLIM GUJAR (Muslim),HASHMI,gov
68,SAINI (Muslim),PATHAN,mf_shadi_jeevansathi
59,MUSLIM SARDAR (Muslim),MUSLIM SARDAR,gov
1,BANJARA (Muslim),"RANGREZ, MEKRANI, KHAN, MAKRANI",mf_shadi_jeevansathi
37,MUSLIM DARJI (Muslim),"OSTAGAR, MUSLIM DARJI, SIDDIQUI, IDRISHI",gov
58,MUSLIM SANPUI (Muslim),"MUSLIM SANPUI, SAPUI",gov
13,GUJJAR (Muslim),"GUJAR, KHAN, GUZAR, GUJJAR(MUSLIM)",mf_jeevansathi
60,MUSLIM TELI (Muslim),"KHAN, SIDDIQUI, MALIK, ALI",gov
33,MUSLIM BHATIYARA (Muslim),MUSLIM BHATIYARA,gov
34,MUSLIM BISWAS (Muslim),MUSLIM BISWAS,gov
41,MUSLIM HALWAI (Muslim),ALI,gov
24,MANG (Muslim),MADARI,mf
36,MUSLIM DAFADAR (Muslim),MUSLIM DAFADAR,gov
23,MALIK (Muslim),"VAJIR, SAYYAD, MALIK",mf
65,QURESHI (Muslim),QURESHI,gov
48,MUSLIM MALI (Muslim),MUSLIM MALI,gov
49,MUSLIM MANYAR (Muslim),"MUSLIM MANYAR, MANIYAAR, MANERI",gov
19,KHOTTA MUSLIM (Muslim),KHOTTA MUSLIM,gov
74,SUNNI (Muslim),SUNNI,mf_shadi_jeevansathi
72,SHEIKH SARVARI (Muslim),"PEERAHI, SHEIKH SARVARI",gov
20,LOHAR (Muslim),"LUHAR SAIFI, SHER, SAIFI",mf_jeevansathi
30,MUSLIM (Muslim),"MUSLIM, MUJAHID, SHAIK, LABBAI, DUDEKULA, BOHR...",mf
2,BELDAR (Muslim),MUSLIM BELDAR,mf_jeevansathi
56,MUSLIM RAJPUT (Muslim),"SULEMANI, QURESHI, GADDI, KHAN, IRAQI, FAKIR, ...",gov
8,DHIMAR (Muslim),"BHISTI, BHATIYAR, DOGARWAR, SHEIKH-ABBASI",mf
67,RANGHAR (Muslim),"KHAN, RANGHAR",mf
55,MUSLIM RAJMISTRI (Muslim),MUSLIM RAJMISTRI,gov
61,NAIR (Muslim),SUNNI,mf_shadi_jeevansathi
31,MUSLIM BARUJIBI (Muslim),MUSLIM BARUJIBI,gov
63,PATHAN (Muslim),"MIRZA, KHAN, PATHAN",mf
26,MOMIN (Muslim),"JULAHA, ANSAR, MOMIN",mf
25,MANSUR (Muslim),"MANSUR, KHAN",mf
69,SAIYED (Muslim),"HUSSAIN, RIZVI, KAZI, SAIYED",mf
53,MUSLIM PENCHI (Muslim),MUSLIM PENCHI,gov
71,SHEIKH (Muslim),"SIDDIQUI, DUDEKULA, BOHRA, FAROOQ, SHEIKH, KHA...",mf
73,SIHAMUSLIM (Muslim),SIHAMUSLIM,mf
22,MAL MUSLIM (Muslim),MAL MUSLIM,gov
62,PAHADIA MUSLIM (Muslim),PAHADIA MUSLIM,gov
51,MUSLIM NAI (Muslim),"SULEMANI, BALWAR, TURKATA",gov
54,MUSLIM PIYADA (Muslim),MUSLIM PIYADA,gov
32,MUSLIM BHANGI (Muslim),"MUSLIM RELIGION BHANGI, LALBEG, KHAKROB, MEHTA...",gov
14,JAT (Muslim),MALIK,mf_shadi_jeevansathi
75,TELI (Muslim),"IDRISHI, TELI MALIK, MALIK, JULAHA, PINDARI",mf_shadi_jeevansathi
17,KHAN (Muslim),"PATHAN, KHAN",mf
21,MAJHI (Muslim),PATNI MUSLIM,mf
18,KHATI (Muslim),"KASAB, QURESHI",mf
66,RAJPUT (Muslim),QURESHI,mf_shadi_jeevansathi

In [129]:
df_hindu

,Caste,Subcastes,source
0,ADIWASI (Hindu),"BHENIL, GOND, DHIMAR, BINJHWAR, KANWAR, BHILAL...",mf
1,AHIR (Hindu),"BARGAH, THETHWAR, AYAR, LALHARIA, GAWALI, RAO,...",mf_jeevansathi
2,ANSARI (Hindu),ANSARI,mf
3,BADHAI (Hindu),"BADHRIA, KHARADI, KHATI, DHEEMAN, MAGHIYA, BAD...",mf_jeevansathi
4,BANIYA (Hindu),"ASRATI, SINGLA, KANSAL, ORIYABANIYA, TUREHA, B...",mf
...,...,...,...
66,SUNNI (Hindu),SAMRATH,mf_shadi_jeevansathi
67,TARKHAN (Hindu),"VISHWAKARMA, TARKHAN, RAMGARHI, BADHAI, DHIMAN",mf
68,TELI (Hindu),"DOBAILE, HIRONDHI, ROGANGAR, HANSI, SAMANI, KU...",mf_shadi_jeevansathi
69,THATARI (Hindu),"THATARI, KANSARI",mf
70,VADDI (Hindu),"SAMPANGI, PALLA, VADDI, VALMIKI, NAIKA, KUDARI...",mf

In [130]:
df_hindu.to_csv("hindu_castes.csv", index=False)

In [131]:
df_muslim_only.to_csv("final_muslim_castes.csv", index=False)

In [132]:
df = pd.read_csv("final_muslim_castes.csv")

In [133]:
df

,Caste,Subcastes,source
0,ADIWASI (Muslim),KHAN,mf
1,BANJARA (Muslim),"RANGREZ, MEKRANI, KHAN, MAKRANI",mf_shadi_jeevansathi
2,BELDAR (Muslim),MUSLIM BELDAR,mf_jeevansathi
3,BHANGI (Muslim),"MALKANA, MEHTAR, HALALKHOR",mf
4,BHILALA (Muslim),MUKATIB,mf
...,...,...,...
72,SHEIKH SARVARI (Muslim),"PEERAHI, SHEIKH SARVARI",gov
73,SIHAMUSLIM (Muslim),SIHAMUSLIM,mf
74,SUNNI (Muslim),SUNNI,mf_shadi_jeevansathi
75,TELI (Muslim),"IDRISHI, TELI MALIK, MALIK, JULAHA, PINDARI",mf_shadi_jeevansathi
76,VADDI (Muslim),"DUDEKULA, PATHAN, SHAIK, SAYED",mf

In [134]:


# Convert 'Subcastes' column from comma-separated strings to Python lists
df["Subcastes"] = (
    df["Subcastes"]
    .fillna("")  # Replace NaNs with empty strings
    .astype(str)  # Ensure string type
    .apply(lambda x: [s.strip() for s in x.split(",") if s.strip()])  # Split and clean
)

# Optional: Save to a new file
# df.to_csv("final_muslim_castes_subcastes_as_list.csv", index=False)

# View first few rows
print(df.head())

              Caste                          Subcastes                source
0  ADIWASI (Muslim)                             [KHAN]                    mf
1  BANJARA (Muslim)  [RANGREZ, MEKRANI, KHAN, MAKRANI]  mf_shadi_jeevansathi
2   BELDAR (Muslim)                    [MUSLIM BELDAR]        mf_jeevansathi
3   BHANGI (Muslim)       [MALKANA, MEHTAR, HALALKHOR]                    mf
4  BHILALA (Muslim)                          [MUKATIB]                    mf

In [135]:
df.to_csv("final_muslim_castes.csv", index=False)

In [136]:

# Convert 'Subcastes' column from comma-separated strings to Python lists
df_hindu["Subcastes"] = (
    df_hindu["Subcastes"]
    .fillna("")  # Replace NaNs with empty strings
    .astype(str)  # Ensure string type
    .apply(lambda x: [s.strip() for s in x.split(",") if s.strip()])  # Split and clean
)

# Optional: Save to a new file
# df.to_csv("final_muslim_castes_subcastes_as_list.csv", index=False)

# View first few rows
df_hindu.head()

,Caste,Subcastes,source
0,ADIWASI (Hindu),"[BHENIL, GOND, DHIMAR, BINJHWAR, KANWAR, BHILA...",mf
1,AHIR (Hindu),"[BARGAH, THETHWAR, AYAR, LALHARIA, GAWALI, RAO...",mf_jeevansathi
2,ANSARI (Hindu),[ANSARI],mf
3,BADHAI (Hindu),"[BADHRIA, KHARADI, KHATI, DHEEMAN, MAGHIYA, BA...",mf_jeevansathi
4,BANIYA (Hindu),"[ASRATI, SINGLA, KANSAL, ORIYABANIYA, TUREHA, ...",mf

In [137]:
df_hindu.to_csv("hindu_castes.csv", index=False)

In [138]:
hindu_caste = pd.read_csv("hindu_castes.csv")

In [139]:
final_hindu_muslim = pd.concat([df_muslim_only, hindu_caste], ignore_index=True)

In [140]:
final_hindu_muslim

,Caste,Subcastes,source
0,ADIWASI (Muslim),KHAN,mf
1,BANJARA (Muslim),"RANGREZ, MEKRANI, KHAN, MAKRANI",mf_shadi_jeevansathi
2,BELDAR (Muslim),MUSLIM BELDAR,mf_jeevansathi
3,BHANGI (Muslim),"MALKANA, MEHTAR, HALALKHOR",mf
4,BHILALA (Muslim),MUKATIB,mf
...,...,...,...
143,SUNNI (Hindu),['SAMRATH'],mf_shadi_jeevansathi
144,TARKHAN (Hindu),"['VISHWAKARMA', 'TARKHAN', 'RAMGARHI', 'BADHAI...",mf
145,TELI (Hindu),"['DOBAILE', 'HIRONDHI', 'ROGANGAR', 'HANSI', '...",mf_shadi_jeevansathi
146,THATARI (Hindu),"['THATARI', 'KANSARI']",mf
147,VADDI (Hindu),"['SAMPANGI', 'PALLA', 'VADDI', 'VALMIKI', 'NAI...",mf

In [141]:
final_hindu_muslim.to_csv("final_hindu_muslim_castes.csv", index=False)

In [142]:
final_hindu_muslim.rename(columns={"Subcastes": "subcastes"}, inplace=True)

In [143]:
muslim = pd.read_csv("final_muslim_castes.csv")

In [144]:
muslim

,Caste,Subcastes,source
0,BANJARA (Muslim),"['RANGREZ', 'MEKRANI', 'KHAN', 'MAKRANI']",mf_shadi_jeevansathi
1,BELDAR (Muslim),['MUSLIM BELDAR'],mf_jeevansathi
2,BHANGI (Muslim),"['MALKANA', 'MEHTAR', 'HALALKHOR']",mf
3,BHILALA (Muslim),['MUKATIB'],mf
4,CHIKWA (Muslim),"['QASSAI', 'CHIKWA QASSAB', 'QURAISHI']",gov
...,...,...,...
66,SHEIKH (Muslim),"['SIDDIQUI', 'DUDEKULA', 'BOHRA', 'FAROOQ', 'S...",mf
67,SHEIKH SARVARI (Muslim),"['PEERAHI', 'SHEIKH SARVARI']",gov
68,SIHAMUSLIM (Muslim),['SIHAMUSLIM'],mf
69,TELI (Muslim),"['IDRISHI', 'TELI MALIK', 'MALIK', 'JULAHA', '...",mf_shadi_jeevansathi
70,VADDI (Muslim),"['DUDEKULA', 'PATHAN', 'SHAIK', 'SAYED']",mf

In [145]:
hindu = pd.read_csv("hindu_castes.csv")

In [146]:
hindu

,Caste,Subcastes,source
0,ADIWASI (Hindu),"['BHENIL', 'GOND', 'DHIMAR', 'BINJHWAR', 'KANW...",mf
1,AHIR (Hindu),"['BARGAH', 'THETHWAR', 'AYAR', 'LALHARIA', 'GA...",mf_jeevansathi
2,BADHAI (Hindu),"['BADHRIA', 'KHARADI', 'KHATI', 'DHEEMAN', 'MA...",mf_jeevansathi
3,BANIYA (Hindu),"['ASRATI', 'SINGLA', 'KANSAL', 'ORIYABANIYA', ...",mf
4,BANJARA (Hindu),"['SUGALI.', 'DHALIA', 'LAMAN BANJARA', 'DHURIY...",mf_shadi_jeevansathi
5,BELDAR (Hindu),"['BHATI', 'SUNKAR', 'OD', 'TAWAR', 'BELDAR']",mf_jeevansathi
6,BHANGI (Hindu),"['BHANGI', 'LALBEGI', 'BALMIK', 'BARWASIA', 'R...",mf
7,BHILALA (Hindu),"['SETIA', 'NARGESH', 'BAKAULEY', 'SHAITE', 'BA...",mf
8,BRAHMAN (Hindu),"['SAMANTA', 'TRIVEDI', 'PRAJAPATI', 'HAVASALA'...",mf
9,CHIKWA (Hindu),"['CHIKWA', 'KASAI', 'CHAK', 'CHIKVI', 'KASSAB']",gov
10,DANGASHIA (Hindu),['DANGASHIA'],gov
11,DHIMAR (Hindu),"['KAMDAY', 'GAUTAM', 'KHEWAT', 'KEWAT', 'VRITI...",mf
12,GAWLI (Hindu),['GAWLI'],gov
13,GHUMAIR (Hindu),['GHUMAIR'],mf
14,GOLA (Hindu),"['GOLLA', 'GOUDIA GOLA', 'LAXMINARAYAN GOLA', ...",gov
15,GORI (Hindu),['GORI'],mf
16,GUJJAR (Hindu),"['GOHIL', 'PATEL', 'GUJARA', 'MAHESHWARI', 'KA...",mf_jeevansathi
17,JAT (Hindu),"['MAUN', 'LUNJ', 'HER', 'PRAJAPATI', 'PAYAL', ...",mf_shadi_jeevansathi
18,JHANGRA BRAHMAN (Hindu),"['JANGID BRAHMAN', 'TARKHAN', 'JHANGRA-BRAHMAN...",gov
19,JULAHA (Hindu),"['KEER', 'KABIRPATH', 'TARIYA', 'ANSARI', 'KAB...",mf_jeevansathi
20,KANJARA â€“ BHATTA (Hindu),"['KANJIRBHAT', 'KANJARA â€“ BHATTA', 'KHANJARBHA...",gov
21,KHANDAYAT (Hindu),"['CHASA', 'ORIYAMUNDA', 'MUNDA', 'ODUKHANDAYAT...",mf_jeevansathi
22,KHANDELWAL (Hindu),['KHANDELWAL'],mf_shadi
23,KHANDNALS (Hindu),['KHANDNALS'],gov
24,KHANDU (Hindu),"['GUPTA', 'KHANDU']",mf
25,KHANGAR (Hindu),"['MIRDHA', 'KHANGAR', 'KANERA']",gov
26,KHANGHERA (Hindu),['KHANGHERA'],gov
27,KHANT (Hindu),['KHANT'],gov
28,KHATI (Hindu),"['CHIKWA', 'KASAI', 'KHATHIYA', 'KHATI', 'JAGA...",mf
29,KHETRIYA (Hindu),"['MAHANAIK', 'ORHKHANDAYAT', 'KHETRIYA']",mf
30,KOLI (Hindu),"['KHARWA', 'DONGAR KOLI', 'KOLI PATEL', 'MAHAV...",mf_jeevansathi
31,KOLI KHANIA (Hindu),['KOLI KHANIA'],gov
32,KUPADHAR (Hindu),"['KUSHIARI', 'PARH', 'KUPADHAR']",gov
33,LOHAR (Hindu),"['WADHAI', 'GOHIL', 'BAWRI', 'KHATI', 'NADRA',...",mf_jeevansathi
34,MAJHI (Hindu),"['KUSMETE', 'MAJHI', 'BHATWAR']",mf
35,MANG (Hindu),"['RADHE MANG', 'MANG GARODI', 'GARUDI', 'MANG'...",mf
36,MUCHI (Hindu),"['RISHI', 'RAVIDAS', 'MUCHI']",gov
37,MUGHAL (Hindu),"['JOSHI', 'RATHORE', 'MEENA']",mf
38,NAIR (Hindu),"['PILLAI', 'THIYA', 'CHETTIAR', 'KURUP', 'VELU...",mf_shadi_jeevansathi
39,NEYGI (Hindu),"['THOGATAGERA', 'THOGATARU', 'LINGAYAT KURUSHI...",gov
40,PATHAN (Hindu),"['RAIGAR', 'LEELGA R', 'PAWAR', 'BHATI', 'SOLA...",mf
41,PINJARA (Hindu),"['NADDAF', 'SHAH', 'KABRAKHODU', 'DHUNIYA', 'B...",mf
42,RAJPUT (Hindu),"['BHARMORIA', 'BHADAURIYA', 'SAKALANI', 'BARWA...",mf_shadi_jeevansathi
43,SAINI (Hindu),"['SAKE', 'MALI', 'SAINI', 'SHAKYA']",mf_shadi_jeevansathi
44,SUDI (Hindu),"['KESARWANI', 'SINDURIYA- BANIA', 'RONIYAR', '...",gov
45,SUNNI (Hindu),['SAMRATH'],mf_shadi_jeevansathi
46,TARKHAN (Hindu),"['VISHWAKARMA', 'TARKHAN', 'RAMGARHI', 'BADHAI...",mf
47,TELI (Hindu),"['DOBAILE', 'HIRONDHI', 'ROGANGAR', 'HANSI', '...",mf_shadi_jeevansathi
48,THATARI (Hindu),"['THATARI', 'KANSARI']",mf
49,VADDI (Hindu),"['SAMPANGI', 'PALLA', 'VADDI', 'VALMIKI', 'NAI...",mf

In [148]:
import pandas as pd


# Clean the Caste column by removing '(Hindu)' and 'Hindu', then stripping whitespace
hindu["Caste"] = (
    hindu["Caste"]
    .str.replace(r"\(Hindu\)", "", regex=True)
    .str.replace("Hindu", "", regex=False)
    .str.strip()
)

# Optional: Save the cleaned file
# df.to_csv("final_muslim_castes_cleaned.csv", index=False)

# Preview the changes
hindu

,Caste,Subcastes,source
0,ADIWASI,"['BHENIL', 'GOND', 'DHIMAR', 'BINJHWAR', 'KANW...",mf
1,AHIR,"['BARGAH', 'THETHWAR', 'AYAR', 'LALHARIA', 'GA...",mf_jeevansathi
2,BADHAI,"['BADHRIA', 'KHARADI', 'KHATI', 'DHEEMAN', 'MA...",mf_jeevansathi
3,BANIYA,"['ASRATI', 'SINGLA', 'KANSAL', 'ORIYABANIYA', ...",mf
4,BANJARA,"['SUGALI.', 'DHALIA', 'LAMAN BANJARA', 'DHURIY...",mf_shadi_jeevansathi
5,BELDAR,"['BHATI', 'SUNKAR', 'OD', 'TAWAR', 'BELDAR']",mf_jeevansathi
6,BHANGI,"['BHANGI', 'LALBEGI', 'BALMIK', 'BARWASIA', 'R...",mf
7,BHILALA,"['SETIA', 'NARGESH', 'BAKAULEY', 'SHAITE', 'BA...",mf
8,BRAHMAN,"['SAMANTA', 'TRIVEDI', 'PRAJAPATI', 'HAVASALA'...",mf
9,CHIKWA,"['CHIKWA', 'KASAI', 'CHAK', 'CHIKVI', 'KASSAB']",gov
10,DANGASHIA,['DANGASHIA'],gov
11,DHIMAR,"['KAMDAY', 'GAUTAM', 'KHEWAT', 'KEWAT', 'VRITI...",mf
12,GAWLI,['GAWLI'],gov
13,GHUMAIR,['GHUMAIR'],mf
14,GOLA,"['GOLLA', 'GOUDIA GOLA', 'LAXMINARAYAN GOLA', ...",gov
15,GORI,['GORI'],mf
16,GUJJAR,"['GOHIL', 'PATEL', 'GUJARA', 'MAHESHWARI', 'KA...",mf_jeevansathi
17,JAT,"['MAUN', 'LUNJ', 'HER', 'PRAJAPATI', 'PAYAL', ...",mf_shadi_jeevansathi
18,JHANGRA BRAHMAN,"['JANGID BRAHMAN', 'TARKHAN', 'JHANGRA-BRAHMAN...",gov
19,JULAHA,"['KEER', 'KABIRPATH', 'TARIYA', 'ANSARI', 'KAB...",mf_jeevansathi
20,KANJARA â€“ BHATTA,"['KANJIRBHAT', 'KANJARA â€“ BHATTA', 'KHANJARBHA...",gov
21,KHANDAYAT,"['CHASA', 'ORIYAMUNDA', 'MUNDA', 'ODUKHANDAYAT...",mf_jeevansathi
22,KHANDELWAL,['KHANDELWAL'],mf_shadi
23,KHANDNALS,['KHANDNALS'],gov
24,KHANDU,"['GUPTA', 'KHANDU']",mf
25,KHANGAR,"['MIRDHA', 'KHANGAR', 'KANERA']",gov
26,KHANGHERA,['KHANGHERA'],gov
27,KHANT,['KHANT'],gov
28,KHATI,"['CHIKWA', 'KASAI', 'KHATHIYA', 'KHATI', 'JAGA...",mf
29,KHETRIYA,"['MAHANAIK', 'ORHKHANDAYAT', 'KHETRIYA']",mf
30,KOLI,"['KHARWA', 'DONGAR KOLI', 'KOLI PATEL', 'MAHAV...",mf_jeevansathi
31,KOLI KHANIA,['KOLI KHANIA'],gov
32,KUPADHAR,"['KUSHIARI', 'PARH', 'KUPADHAR']",gov
33,LOHAR,"['WADHAI', 'GOHIL', 'BAWRI', 'KHATI', 'NADRA',...",mf_jeevansathi
34,MAJHI,"['KUSMETE', 'MAJHI', 'BHATWAR']",mf
35,MANG,"['RADHE MANG', 'MANG GARODI', 'GARUDI', 'MANG'...",mf
36,MUCHI,"['RISHI', 'RAVIDAS', 'MUCHI']",gov
37,MUGHAL,"['JOSHI', 'RATHORE', 'MEENA']",mf
38,NAIR,"['PILLAI', 'THIYA', 'CHETTIAR', 'KURUP', 'VELU...",mf_shadi_jeevansathi
39,NEYGI,"['THOGATAGERA', 'THOGATARU', 'LINGAYAT KURUSHI...",gov
40,PATHAN,"['RAIGAR', 'LEELGA R', 'PAWAR', 'BHATI', 'SOLA...",mf
41,PINJARA,"['NADDAF', 'SHAH', 'KABRAKHODU', 'DHUNIYA', 'B...",mf
42,RAJPUT,"['BHARMORIA', 'BHADAURIYA', 'SAKALANI', 'BARWA...",mf_shadi_jeevansathi
43,SAINI,"['SAKE', 'MALI', 'SAINI', 'SHAKYA']",mf_shadi_jeevansathi
44,SUDI,"['KESARWANI', 'SINDURIYA- BANIA', 'RONIYAR', '...",gov
45,SUNNI,['SAMRATH'],mf_shadi_jeevansathi
46,TARKHAN,"['VISHWAKARMA', 'TARKHAN', 'RAMGARHI', 'BADHAI...",mf
47,TELI,"['DOBAILE', 'HIRONDHI', 'ROGANGAR', 'HANSI', '...",mf_shadi_jeevansathi
48,THATARI,"['THATARI', 'KANSARI']",mf
49,VADDI,"['SAMPANGI', 'PALLA', 'VADDI', 'VALMIKI', 'NAI...",mf

In [150]:
merged = pd.concat([hindu, muslim], ignore_index=True)

In [151]:
merged

,Caste,Subcastes,source
0,ADIWASI,"['BHENIL', 'GOND', 'DHIMAR', 'BINJHWAR', 'KANW...",mf
1,AHIR,"['BARGAH', 'THETHWAR', 'AYAR', 'LALHARIA', 'GA...",mf_jeevansathi
2,BADHAI,"['BADHRIA', 'KHARADI', 'KHATI', 'DHEEMAN', 'MA...",mf_jeevansathi
3,BANIYA,"['ASRATI', 'SINGLA', 'KANSAL', 'ORIYABANIYA', ...",mf
4,BANJARA,"['SUGALI.', 'DHALIA', 'LAMAN BANJARA', 'DHURIY...",mf_shadi_jeevansathi
...,...,...,...
116,SHEIKH (Muslim),"['SIDDIQUI', 'DUDEKULA', 'BOHRA', 'FAROOQ', 'S...",mf
117,SHEIKH SARVARI (Muslim),"['PEERAHI', 'SHEIKH SARVARI']",gov
118,SIHAMUSLIM (Muslim),['SIHAMUSLIM'],mf
119,TELI (Muslim),"['IDRISHI', 'TELI MALIK', 'MALIK', 'JULAHA', '...",mf_shadi_jeevansathi
120,VADDI (Muslim),"['DUDEKULA', 'PATHAN', 'SHAIK', 'SAYED']",mf

In [149]:
non_muslim_df

            Caste                                     subcastes source
0          AARAKH  [MOOTHI, YADAV, AARAKH, ARAKVANSHIYA, ARAKH]     mf
1          ABBASI                      [ABBASI, BHISHTI, SAKKA]    gov
2           ABDAL                                       [ABDAL]    gov
3       ABLAKAROR                                   [ABLAKAROR]     mf
4            ABOR                                        [ABOR]    gov
...           ...                                           ...    ...
2216  YOGEESWARAR                                 [YOGEESWARAR]    gov
2217         YOGI                 [JOGI, JUGI NATH, NATH, YOGI]     mf
2218    YRAKITHER                                   [YRAKITHER]     mf
2219       ZAMRAL                                      [ZAMRAL]    gov
2220          ZOU                                         [ZOU]    gov

[2120 rows x 3 columns]

In [152]:
merged.rename(columns={"Subcastes": "subcastes"}, inplace=True)

In [153]:
final_df = pd.concat([non_muslim_df, merged], ignore_index=True)

In [154]:
final_df

,Caste,subcastes,source
0,AARAKH,"[MOOTHI, YADAV, AARAKH, ARAKVANSHIYA, ARAKH]",mf
1,ABBASI,"[ABBASI, BHISHTI, SAKKA]",gov
2,ABDAL,[ABDAL],gov
3,ABLAKAROR,[ABLAKAROR],mf
4,ABOR,[ABOR],gov
...,...,...,...
2236,SHEIKH (Muslim),"['SIDDIQUI', 'DUDEKULA', 'BOHRA', 'FAROOQ', 'S...",mf
2237,SHEIKH SARVARI (Muslim),"['PEERAHI', 'SHEIKH SARVARI']",gov
2238,SIHAMUSLIM (Muslim),['SIHAMUSLIM'],mf
2239,TELI (Muslim),"['IDRISHI', 'TELI MALIK', 'MALIK', 'JULAHA', '...",mf_shadi_jeevansathi
2240,VADDI (Muslim),"['DUDEKULA', 'PATHAN', 'SHAIK', 'SAYED']",mf

In [155]:
final_df.to_csv("final_caste_with_source_1.csv", index=False)